# Generated by Django 3.0.2 on 2020-05-07 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('resultId', models.AutoField(primary_key=True, serialize=False)),
                ('uploadImg', models.ImageField(upload_to='upload')),
                ('compareImg', models.CharField(max_length=48)),
                ('content', models.CharField(max_length=255)),
                ('compareTime', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'result',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('usrid', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=48, null='false')),
                ('avatarUrl', models.CharField(default='http://127.0.0.1:8000/images/avater/buttocks.jpg', max_length=255)),
                ('city', models.CharField(max_length=48)),
                ('country', models.CharField(max_length=48)),
                ('province', models.CharField(max_length=48)),
                ('gender', models.IntegerField(default=1)),
                ('language', models.CharField(max_length=48)),
                ('lastLoginTime', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='YogaImage',
            fields=[
                ('imgid', models.AutoField(primary_key=True, serialize=False)),
                ('yogaName', models.CharField(max_length=48)),
                ('level', models.IntegerField(default=1)),
                ('imgDescription', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='yoga')),
            ],
            options={
                'db_table': 'yogaImage',
            },
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('studyRecordId', models.AutoField(primary_key=True, serialize=False)),
                ('resultid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogaMaster.Result')),
                ('usrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogaMaster.User')),
            ],
            options={
                'db_table': 'studyRecord',
            },
        ),
        migrations.AddField(
            model_name='result',
            name='imgid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogaMaster.YogaImage'),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('favoritesId', models.AutoField(primary_key=True, serialize=False)),
                ('imgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogaMaster.YogaImage')),
                ('usrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogaMaster.User')),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
    ]
