# Generated by Django 3.0.2 on 2020-02-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaMaster', '0002_auto_20200208_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='compareImg',
            field=models.ImageField(upload_to='images/result'),
        ),
        migrations.AlterField(
            model_name='result',
            name='uploadImg',
            field=models.ImageField(upload_to='images/upload'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usrProfile',
            field=models.ImageField(upload_to='images/avater'),
        ),
        migrations.AlterField(
            model_name='yogaimage',
            name='image',
            field=models.ImageField(upload_to='images/yoga'),
        ),
    ]
